### ISSUE TITLE
Not working with Tabular Dataset

### ISSUE THREAD

**Issue by vicjoy** [Team-TUD/CTAB-GAN#11]
Hi,

Good day to you Zhao Zilong.

I tried using CTAB_GAN to generate some fake data but I couldn't have a smooth generation. I used this:

synthesizer =  CTABGAN(raw_csv_path = real_path,
                 test_ratio = 0.20,  
                 categorical_columns = ['Target'], 
                 log_columns = [],
                 mixed_columns= {}, 
                 integer_columns = ['Sport', 'TotPkts','TotBytes', 'SrcPkts','DstPkts','SrcBytes','Target'],
                 problem_type= {"Classification": 'Target'},
                 epochs = 10)

I have the following errors:

AttributeError                            Traceback (most recent call last)
AttributeError: 'str' object has no attribute 'rint
TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method

I used the exact numpy 1.21.0 specified.
![image](https://user-images.githubusercontent.com/28909800/176049261-b5810859-8e0d-41d2-b95f-b5f833ac27e3.png)

Please, help me to check and see what I am missing. It worked fine with Adult Data

**Comment by zhao-zilong** [comment]
Hi Vicjoy,

    Seems the training is finished, is that the problem from sampling? I didn't meet this problem before and the error information is very limited, it is difficult to tell the problem.

Zilong

**Comment by vicjoy** [comment]
Thank you for your prompt response.

Here are the details of the error:

![image](https://user-images.githubusercontent.com/28909800/176474274-bde54af2-b354-4341-977c-fdb7779bd7f2.png)

Finished training in 36.167824268341064  seconds.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'str' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     56     try:
---> 57         return bound(*args, **kwds)
     58     except TypeError:

TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: 'str' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7824/1892368471.py in <module>
     15 for i in range(num_exp):
     16     synthesizer.fit()
---> 17     syn = synthesizer.generate_samples()
     18     syn.to_csv(fake_file_root+"/"+ dataset+"_fake_{exp}.csv".format(exp=i), index= False)

~\Desktop\python\old\ctab_gan2\model\ctabgan.py in generate_samples(self)
     67 
     68         sample = self.synthesizer.sample(len(self.raw_df))
---> 69         sample_df = self.data_prep.inverse_prep(sample)
     70 
     71         return sample_df

~\Desktop\python\old\ctab_gan2\model\pipeline\data_preparation.py in inverse_prep(self, data, eps)
    129         if self.integer_columns:
    130             for column in self.integer_columns:
--> 131                 df_sample[column]= (np.round(df_sample[column].values))
    132                 df_sample[column] = df_sample[column].astype(int)
    133 

<__array_function__ internals> in round_(*args, **kwargs)

~\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py in round_(a, decimals, out)
   3737     around : equivalent function; see for details.
   3738     """
-> 3739     return around(a, decimals=decimals, out=out)
   3740 
   3741 

<__array_function__ internals> in around(*args, **kwargs)

~\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py in around(a, decimals, out)
   3312 
   3313     """
-> 3314     return _wrapfunc(a, 'round', decimals=decimals, out=out)
   3315 
   3316 

~\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     64         # Call _wrapit from within the except clause to ensure a potential
     65         # exception has a traceback chain.
---> 66         return _wrapit(obj, method, *args, **kwds)
     67 
     68 

~\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     41     except AttributeError:
     42         wrap = None
---> 43     result = getattr(asarray(obj), method)(*args, **kwds)
     44     if wrap:
     45         if not isinstance(result, mu.ndarray):

TypeError: loop of ufunc does not support argument 0 of type str which has no callable rint method




I was able to use it successfully with your dataset (adult) by ensuring dython lib is in line with the specified version. But even after I used the specified numpy, dython, scipy, etc. I still encountered this problem. 

I have done all I could from my end to ensure it runs with my datasets, it was not going through.

Thanks in advance as you assist me on this.

**Comment by zhao-zilong** [comment]
From here:
68 sample = self.synthesizer.sample(len(self.raw_df))
---> 69 sample_df = self.data_prep.inverse_prep(sample)
we can see that the sample() function is executed. It's the problem of inverse_prep() I think you can same the "sample" to check what it generates.

And from this part:
130 for column in self.integer_columns:
--> 131 df_sample[column]= (np.round(df_sample[column].values))
I think you can output the "column" to see which column give you this trouble.

Since it seems it is dataset related, I can't tell further.

**Comment by vicjoy** [comment]
Thank you so much.

I finally had a breakthrough. One of the columns was responsible for the error. I got it fixed with your suggestions
