### ISSUE TITLE
Treating Continuous Variable with Missing Values as Mix Variable

### ISSUE THREAD

**Issue by amieelxy** [Team-TUD/CTAB-GAN#12]
Hi,

I would like to generate synthetic dataset with your repo, and my continuous column contains missing values. Reference to your article, I treat the continuous column with missing values as mixed variables but the "mixed_columns" parameter for object CTABGAN requires a "dictionary of column name and categorical modes used for "mix" of numeric and categorical distribution". I understand that for the "mortgage" case we should put down mode 0.0 to treat the special meaning of 0, but what mode should I put down for the missing values?

Thank you!

**Comment by zhao-zilong** [comment]
Hi,
  
   Normally if your data contains missing values, you don't need to do anything, check this link of code: 
   https://github.com/Team-TUD/CTAB-GAN/blob/32ec57cc2772e52e325fedff54ab25442cd55bff/model/pipeline/data_preparation.py#L48

  Currently, we will replace the missing value with the string "empty" and treat the column as mixed type, you don't need to do that.

  Best,

Zilong

**Comment by amieelxy** [comment]
Thanks for the prompt response!
