### ISSUE TITLE
Datetime Object

### ISSUE THREAD

**Issue by amieelxy** [Team-TUD/CTAB-GAN#13]
Hi Zilong,

I'm using the CTAB-GAN to generate synthetic data. My dataset contains a datetime column with no missing values and I encounter the error message: could not convert string to float: '2010-04-01'.  Could you please advise if the CTAB-GAN can handle datetime columns?

Thank you for your time. 

![image](https://user-images.githubusercontent.com/92274777/178132622-bc522a63-d05a-469f-92f8-8d62a67a3fba.png)
![image](https://user-images.githubusercontent.com/92274777/178132638-f70d442b-6971-4064-86fd-0e496896137a.png)

**Comment by zhao-zilong** [comment]
Hi,

    We originally planned to do that, but in the end no. I don't think we can handle date-time, I think you need to specify it as categorical column for now.

   But actually one way to deal that, which is original what we want to do, is to first sort your date, and then only use the time-span comparing to the earliest date instead of using the original date. In that case, all your date becomes continuous number.

   Best,

Zilong

**Comment by amieelxy** [comment]
Thanks for the advice!
