### ISSUE TITLE
How to specify decimal places in generated data

### ISSUE THREAD

**Issue by pgschr** [Team-TUD/CTAB-GAN#14]
My input data has integers and decimals with two places, but the generated data has eight decimal places, even when the input is an integer. Is there a way to specify number of decimal places, or data type (decimal/integer) or I need to do that manually after the data generation?

**Comment by zhao-zilong** [comment]
Hi,  
     Check our ctab-gan+ code here: https://github.com/Team-TUD/CTAB-GAN-Plus/blob/main/Experiment_Script_Adult.ipynb  In general, the ctab-gan+ code is more stable than ctab-gan.
     In this example, you can specify which column is integer so that you will generate as integer. But to specify number of decimal places, we didn't support this function, I think you can edit the code of integer transformation part.
 Zilong

**Comment by pgschr** [comment]
Thanks, I will switch to ctab-gan+ and use the integers option. Question: Let's say that my input dataset is col1, col2, col3 and I generate synthetic data with ctab-gan+, when I generate the new values, can the library consider the correlation between the columns?

**Comment by zhao-zilong** [comment]
Hi again, I don't think we specifically "consider" their correlations in the code, but the GAN algorithm and the proposed losses take care of that. So my answer is YES.
