### ISSUE TITLE
Dealing with continuous columns

### ISSUE THREAD

**Issue by PradKalkar** [Team-TUD/CTAB-GAN#15]
Hi. I know that all the columns in my dataset are continuous variables. So, should I specify these columns in "mixed_columns" while initializing the synthesizer? If yes, what value should I specify for the mode since we have to specify these columns as a dictionary? Should I always keep it 0.0?

**Comment by zhao-zilong** [comment]
Hi @PradKalkar  if they are just continuous, you don't need to specify anything. For mixed_columns, only if you have the column say it contains "-100" or some other continuous value, then you specify the value '-100' for this column. it's not always 0, it depends the outstanding value you have in the column.

**Comment by PradKalkar** [comment]
Ok. So, basically if all the columns are continuous, I have to leave all the column lists in the initialization blank, right?

**Comment by zhao-zilong** [comment]
yes, it is.

**Comment by PradKalkar** [comment]
Alright. Thanks a lot for your quick response!
