### ISSUE TITLE
Handling large datasets (with a large number of rows)

### ISSUE THREAD

**Issue by PradKalkar** [Team-TUD/CTAB-GAN#16]
Hi. When I use this method on a large dataset (in terms of number of rows), I am requiring a lot of time for the bgm fitting per column - around 10-15 mins or so. Is there any way to modify the code so that I cut down on time.

**Comment by zhao-zilong** [comment]
Hi @PradKalkar  you can try ctab-gan+ (https://github.com/Team-TUD/CTAB-GAN-Plus) code, and specify all the continuous columns in "general_transform". Then it will treat all the continuous columns using only min-max normalisation instead of BGM.

**Comment by PradKalkar** [comment]
Alright. Thanks!

**Comment by PradKalkar** [comment]
And if I want to try with bgm in CTAB-GAN+ code in which feature cols have NaN values, then I would just need to specify the label col name in categorical list and keep other lists empty? Am I right?

**Comment by zhao-zilong** [comment]
Using bgm in CTAB-GAN+ does not need to specify anything. For column containing "NaN", you don't need to anything, the code will take care of it.

**Comment by PradKalkar** [comment]
Alright. Thanks!
