### ISSUE TITLE
Possible issues in model training if label column not specified in categorical list

### ISSUE THREAD

**Issue by PradKalkar** [Team-TUD/CTAB-GAN#17]
Hey, just have a small doubt. If I don't specify label column (I am having a binary classification task) in the list of categorical columns while initialising the synthesizer, would it be automatically detected? Does not specifying label col in categorical col list affect the GAN training?

**Comment by zhao-zilong** [comment]
Hi @PradKalkar If you don't specify that, ctab-gan will treat it as continuous, then you may generate values that are not integer (in your case o or 1?).  You can still do some post processing for it. Do you have any specific reason that you don't want to list it in the categorical column?

**Comment by PradKalkar** [comment]
No specific reason. Actually I forgot to add the label column in the categorical list. But, the data on which I was training has all rows belonging to the same label. So, would forgetting to add label to cateforical list affect the generated data quality as compared to mentioning it in categorical list?

**Comment by zhao-zilong** [comment]
Oh, if all the data you train are belonging to the same label, then I think you don't need to generate this column, you can just single it out and generate only others. In your case, if you already train the model, I think you can just manually replace the generated label column using your given one.

**Comment by PradKalkar** [comment]
Got it. Thanks a lot for the quick response!
