### ISSUE TITLE
Saving fake data to .csv in jupyter notebook

### ISSUE THREAD

**Issue by jeiglsperger** [Team-TUD/CTAB-GAN#2]
Hi,

this line 
`syn.to_csv(fake_file_root+"/"+dataset+"/"+dataset+"_fake_{exp}.csv".format(exp=i), index= False)`
in the third cell of the juypter notebook example won't work if the directory `Fake_Datasets/Adult` is not created yet (as it is in the repo), as pandas does not create directories if they are not existing. Maybe create the directory already in the repo so one can just clone it or do something like 
```
outdir = 'Fake_Datasets/Adult'
if not os.path.exists(outdir):
    os.mkdir(outdir)
syn.to_csv(outdir+"/"+dataset+"_fake_{exp}.csv".format(exp=i), index= False)
```
if I'm not wrong.

Kind regards!

**Comment by zhao-zilong** [comment]
yeah, you are right, we have this folder locally, but since it's empty, it didn't show up in this git. I will try to correct it. Thanks

**Comment by zhao-zilong** [comment]
The folder is up to the git
