### ISSUE TITLE
BayesianGaussianMixture

### ISSUE THREAD

**Issue by Tolux5000** [Team-TUD/CTAB-GAN#21]
Hi, how do I fix this please? Thanks.

![error](https://github.com/Team-TUD/CTAB-GAN/assets/120363015/0925b0ca-50ea-4edf-95ad-42cdb92d0436)

**Comment by zhao-zilong** [comment]
Hi @Tolux5000 

You can either 
1. downgrade your sklearn version to `sklearn==0.24.1` or 

2. you can edit the line 94 like

```
n_components = self.n_clusters,
```
I think both way can solve this error.

**Comment by limhasic** [comment]
which file in line 94 ? 
i changed transformer.py but 

File /mnt/CTAB-GAN/model/synthesizer/transformer.py:116, in DataTransformer.fit(self)
    111     self.output_dim += 1 + np.sum(comp)
    113 elif info['type'] == "mixed":
    114     
    115     # in case of mixed columns, two bgm models are used
--> 116     gm1 = BayesianGaussianMixture(
    117         n_components = self.n_clusters,
    118         weight_concentration_prior_type='dirichlet_process',
    119         weight_concentration_prior=0.001, max_iter=100,
    120         n_init=1,random_state=42)

but same error occur 

TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 5 keyword-only arguments) were given

So,
I changed all BayesianGaussianMixtures to n_components = self.n_clusters, and it worked.

**Comment by zhao-zilong** [comment]
Hi @limhasic 

yeah, you need to change all the parts to this to make it work.
