### ISSUE TITLE
TypeError: loop of ufunc does not support argument 0 of type float which has no callable log method

### ISSUE THREAD

**Issue by jeiglsperger** [Team-TUD/CTAB-GAN#3]
Hi! 

I have another question about CTAB-GAN. Did you also encounter the error above while developing the model?
I guess it's because some values in the dataset (I try to apply my own dataset to CTAB-GAN) are non-float types. But I transformed every numeric column to float now by hand to make sure this is not the case but the error still occurs. Maybe you had the same problem and know a solution from your experience?

**Comment by zhao-zilong** [comment]
Hi,
 
   First,  If you take log, you need to make sure all the value higher than 0. Second, you can output the column where the log method is not successfully called and see which value is the problem.

**Comment by jeiglsperger** [comment]
Thanks, I found the problematic column! Now it works with my own dataset, looks really cool!
