### ISSUE TITLE
ImportError: cannot import name 'compute_associations' from 'dython.nominal'

### ISSUE THREAD

**Issue by femurray** [Team-TUD/CTAB-GAN#5]
Hi, I found this error in evaluation.py. It turns out dython was updated, and compute_associations was removed.

According to http://shakedzy.xyz/dython/modules/nominal/#compute_associations, the compute_associations is replaced by associations(compute_only=True)['corr'].

I edited the code in evaluation.py locally, editing line 10 to import associations instead of compute_associations and replacing "real_corr = compute_associations(real, nominal_columns=cat_cols)" on line 110 with "real_corr = associations(real, nominal_columns=cat_cols, compute_only=True)['corr']".

Line 112 was updated accordingly too.

I think this fixes the issue, just wanted to flag it here in case this affects the code in ways the developers might notice but that I wouldn't.

Thanks

**Comment by Epiphanyyc** [comment]
Thank you! This helps me a lot !
