### ISSUE TITLE
Standardizing data prior to use

### ISSUE THREAD

**Issue by femurray** [Team-TUD/CTAB-GAN#6]
The first question I have is, would it be worth standardizing my datasets before using CTAB-GAN on them? 

I haven't done this so far as the CTAB-GAN tutorial didn't include standardization, but realized after running cWGAN code (which does use standardizing) that it could potentially speed up the time it takes to run CTAB-GAN on each dataset, among other benefits.

Or would doing so mess up the running of CTAB-GAN?

**Comment by zhao-zilong** [comment]
No, you don't need to normalize your data to use CTAB-GAN. It has already implemented mode-specific-normalization for continuous variables and one-hot encoding for categorical variables.

**Comment by femurray** [comment]
Thanks!
