### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 3 positional arguments (and 5 keyword-only arguments) were given

### ISSUE THREAD

**Issue by femurray** [Team-TUD/CTAB-GAN#7]
For my project I remote control a PhD student's PC on campus as it is quicker than my own laptop. I do this so my code can run quicker.

One issue is that CTAB-GAN runs fine (but slow) on my laptop, but can't get going on the PhD PC. I've made sure the python versions are the same, but the same error keeps getting thrown. The details are below.

Traceback (most recent call last):

  Input In [6] in <cell line: 37>
    synthesizer.fit()

  File ~\Desktop\python\CTAB-GAN\model\ctabgan.py:43 in fit
    self.synthesizer.fit(train_data=self.data_prep.df, categorical = self.data_prep.column_types["categorical"],

  File ~\Desktop\python\CTAB-GAN\model\synthesizer\ctabgan_synthesizer.py:333 in fit
    self.transformer.fit()

  File ~\Desktop\python\CTAB-GAN\model\synthesizer\transformer.py:59 in fit
    gm = BayesianGaussianMixture(

TypeError: __init__() takes 1 positional argument but 3 positional arguments (and 5 keyword-only arguments) were given

When I google the error, it says to add the argument "self" in the function __init__(), however, all instances of the function __init__() on the transformer.py file already have "self" as an argument. Do you have any insight into this issue?

**Comment by zhao-zilong** [comment]
This is due to the scikit-learn version. BayesianGaussianMixture function changes its entry during some versions.

**Comment by femurray** [comment]
Thanks!
