### ISSUE TITLE
Any way to generate multiple datasets with same learned model?

### ISSUE THREAD

**Issue by femurray** [Team-TUD/CTAB-GAN#8]
Hi,

So when running the CTAB-GAN code as in the example on this repo, CTAB-GAN learns the inputted dataset and generates a new fake dataset.

Is there any way to run it so it learns the input dataset once, and then generates multiple fake datasets?

The alternative is to run the example code every time, which means the code has to learn the input dataset every time.

Kind regards,

Fergal

**Comment by zhao-zilong** [comment]
Hi Femurray,

   You don't need to train it every time. 
    One way is to keep run following code in the ipynb (of course, with a different `i` each time):

```
    syn = synthesizer.generate_samples()
    syn.to_csv(fake_file_root+"/"+dataset+"/"+ dataset+"_fake_{exp}.csv".format(exp=i), index= False)
```

   Otherwise, you can also save the synthesizer object, something like:

```
import pickle
with open('synthesizer_object.pk', 'wb') as synthesizer_object:
    pickle.dump(synthesizer, synthesizer_object)
```

Then reload it like that:
```
with open('synthesizer_object.pk', 'rb') as synthesizer_object:
    synthesizer_reloaded = pickle.load(synthesizer_object)
```

Best,

Zilong

**Comment by femurray** [comment]
Perfect, thank you!
