### ISSUE TITLE
Generating data without problem type

### ISSUE THREAD

**Issue by erenarkangil** [Team-TUD/CTAB-GAN#9]
Hi there,

I wanted to use this repo to generate fake cencus data for upsampling my microdata. However, I am confused with the ''problem-type'' part. I checked the repo and It seems it does not work without giving ml specific problem, which I do not have yet. Still I tried this code:

synthesizer =  CTABGAN('/Users/erensmacbook/Desktop/hay.csv',
                 test_ratio = 0.20,  
                 categorical_columns = ['INDP','AGEP','INCP'], 
                 epochs = 1,
                      problem_type= {"REGRESSION": 'SEXP'}) 

Where the categorical variables are income, age, job and sex groups. It seems worked, but then I got this error when I tried to generate sample data

~/ctab/model/ctabgan.py in generate_samples(self)
     66 
     67         sample = self.synthesizer.sample(len(self.raw_df))
---> 68         sample_df = self.data_prep.inverse_prep(sample)
     69 
     70         return sample_df

KeyError: 'age'

Although , I dont have age in my dataset. Is it given, it is not possible to use this repo for various dataset?

Thanks

**Comment by zhao-zilong** [comment]
Hi,
    
    Current, CTAB-GAN code only accepts problem_type for "Classification". We indeed update our code in ctab-gan+ code, but we are not releasing it yet. So for regression problem, you can leave the problem_type part as None.

    Best,

Zilong

**Comment by hafidh561** [comment]
> Hi,
> 
> ```
> Current, CTAB-GAN code only accepts problem_type for "Classification". We indeed update our code in ctab-gan+ code, but we are not releasing it yet. So for regression problem, you can leave the problem_type part as None.
> 
> Best,
> ```
> 
> Zilong

When do you release the CTAB-GAN+ code?

**Comment by zhao-zilong** [comment]
Hi,
   
   Thanks for the reminding :) . I'm actually working for a conference deadline now. I would have time to clean the code and release it in 2 weeks (I really hope). So that's why I didn't close this issue. I will reply in this thread once the ctab-gan+ code is online.

   Best,

Zilong

**Comment by zhao-zilong** [comment]
Hi guys (@hafidh561 , @Erenhub ),

    CTAB-GAN+ code is released here: https://github.com/Team-TUD/CTAB-GAN- 
    Now you can indicate that your problem is classification, regression or none. Check the README in that git.

    Best,

Zilong
